### ISSUE TITLE
AttributeError: module 'tensorflow.keras.backend' has no attribute 'get_session'

### ISSUE THREAD

**Issue by kang-hong-29** [nairouz/DynAE#14]
Hi,  when I run the code on Colab, an error posted like the title. I guess it may because of the wrong version of TensorFlow(2.3.0) and Keras(2.4.0) on Colab. Can you give me the proper versions of TensorFlow and Keras? Thanks so much.

**Comment by nairouz** [comment]
tensorflow==1.15.0
Keras==2.2.5

**Comment by kang-hong-29** [comment]
Solved, thank you!
