### ISSUE TITLE
no attribute 'AdamOptimizer'

### ISSUE THREAD

**Issue by PhoQus** [nairouz/DynAE#15]
When trying to run your code I get the following error. Do you have any suggestions on how to fix it?

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-ad2955459a68> in <module>()
      9 tol=0.01
     10 optimizer1=SGD(0.001, 0.9)
---> 11 optimizer2=tf.train.AdamOptimizer(0.0001)
     12 kappa = 3
     13 ws=0.1

AttributeError: module 'tensorflow._api.v2.train' has no attribute 'AdamOptimizer'

**Comment by thehappy1** [comment]
Hi PhoQus, 
the new version of tensorflow is using a different approach. Try this:
tf.train.AdamOptimizer() => tf.optimizers.Adam()
